name: devcherry.com
description: Another tech blog
meta_description: "devcherry.com, Another tech blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: 'http://devcherry.com'
google_analytics: 'UA-71838415-1'
gems: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]

# Details for the RSS feed generator
url:            'http://devcherry.com'
author:         'Artur Malecki'
